# Generated by Django 4.2.30 on 2026-04-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='resources.subject'),
        ),
    ]
